modify

diff --git a/shell b/shell
--- a/shell
+++ b/shell
@@ -1,4 +1,39 @@
 #!/bin/sh
+#=============================================
+#编写高质量的bash脚本
+	1.一定要用简短的标题注释脚本
+	2.要加上足够的注释，这样以后就可以轻松的想起原来编写代码的原因
+	3.应该把脚本的操作记录在日志文件中并加上日期和时间戳，以便日后检查。应该记录成功消息并清除的表达错误消息或条件。\
+		记录脚本的启动和停止时间也可能有意义。可以用tee把消息同时写到日志和标准输出。
+	4.如果脚本要写入日志文件，那么应该创建新的日志文件，并在日志文件名中包含日期，小时，分钟甚至秒。这样的话，在每次\
+		运行脚本时，可以使用简单的find命令循环和压缩脚本的日志
+	5.应该在脚本中加入错误检查逻辑，不要假设任何东西是正确的。
+	6.尽可能在脚本中使用函数和shell脚本库（通过导入另一个脚本）。这样做可以重用经过测试的可靠代码，避免重复编写并减少错误。
+	7.要求对用户提供的输入参数进行筛选。
+		eg.
+		NUMPAR_AMETERS="$#"
+		if [ $NUMPAR_AMETERS != 3 ]; then
+			ehco "Insufficient number of parameter passed!"
+			echo "Please run srcipt in format ./myscript.sh $1 $2 $3"
+			exit 2
+		fi
+	8.考虑在脚本中增加调试模式或功能。比如使用set -x命令
+	9.在脚本中添加对某些事件发出警报的功能。可以使用SNMP命令或听得到的铃声（echo x）发出警报，然后用mail命令发送电子邮件。
+	10.如果用户将像使用交互菜单那样使用您编写的脚本，那么要考虑用户的环境shell和他们有权访问的命令。如果不确定，那么\
+		脚本中的所有命令都应该使用完整路径。
+	11.在bash shell脚本中添加独特的返回码。这样的话，在编写大脚本时，可以根据返回码轻松找到发生错误或问题的准确位置。
+		eg.
+		if [ "$ERRCHECK" != "" ]; then
+			echo "Error Detected : $ERRCHECK ! Cannot continue, exit $EXITVAL value"
+			exit $EXITVAL
+		fi
+	12.邀请其他用户对脚本进行测试。
+	13.如果脚本操作来自用户或数据输入文件的输入数据，那么一定要全面筛选、检查和检验输入数据。操作数据列表的脚本应该可以\
+		处理多个不同的数据列表集。
+	14.对于长时间运行的脚本，考虑在脚本中添加超时功能，以便在n分钟之后终止或停止脚本。
+		stty -icannon min 0 time 1800
+#=============================================
+
 #echo相关参数
 	-e	允许解释转义序列
 	-n	删除输出结果的换行符
